# Generated by Django 5.1.4 on 2024-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="Default Title", max_length=255),
        ),
    ]
